matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: '9'
      env:
        - PACKAGE_PLATFORM=darwin
    - os: linux
      services: docker
      language: generic
      env:
        - PACKAGE_PLATFORM=win32
    - os: linux
      services: docker
      language: generic
      env:
        - PACKAGE_PLATFORM=linux
cache:
  directories:
    - node_modules
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|YARN_|NPM_|CI|TRAVIS|BUILD_|PACKAGE_' | grep -v ' ') \
        -v ${PWD}:/project k0kubun/node-wine:latest \
        /bin/bash -c "cd /project && yarn --link-duplicates --pure-lockfile && yarn build"
    else
      yarn --link-duplicates --pure-lockfile
      yarn build
    fi

before_deploy:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|YARN_|NPM_|CI|TRAVIS|BUILD_|PACKAGE_' | grep -v ' ') \
        -v ${PWD}:/project k0kubun/node-wine:latest \
        /bin/bash -c "cd /project && yarn package"
    else
      yarn package
    fi
deploy:
  provider: releases
  api_key:
    # travis encrypt "APIKEY" --add deploy.api_key -r k0kubun/Nocturn --adapter net-http
    secure: bACy9zaS+r7xpvBiaJfmffxoaoytdMMub8vrUQxH5XHrYYuK664JVqSfusBbZzTeXFuq/0ZGVr954N7622doyMCVShDNLSvvKibSwW8tTOLVz3CIZHtQlF4aHybdh+SOPPLEpJietkebJo0SYinQZXEo1iUL5WemqfgefU8TWjWcryofvj0xlCM5dpXs4v6za17YxRNcKT4MiNNSjt+Ke/DrEJxCYm0r8AIM3h8WpRo6mELXLIOBIRO1AwI+Xo/1+8ibhcJHFQB79pP83rFoZEOO3sE/mqeZ+rK8miD9UY549aOaXX7h8taasMWu4waEF5qunYynDBteR+VY95lf6BPY6556DJ8ieNUjWQ721h4vPch+/VINdNPDTtTmQe6k3SNETw78dvfewWh7Uib7pcBnp/TS5xIyy8ixFbKFPCjC7jcQxFkzACvMg4hIdqrF/7/jtujp3NqWZAR1ephhZzDWnaEsdbthPJWQpckQEab9XKs3UI2S4odIuSRdEn5rB1qv7plH/e1HYahs5Zs3djx7tD1xT1Zsx24ZpTDgah5t0PkNRWDKwdxIXc1P43DFMh64byeOjY+A3kSUbE77q20Xtw1dnAuuSxNJ3GlBq5MjwkeaGZeL57lRyZZ3tGdxAu9jsJadW7+myaTA7D+ZRe2FQa1k5FPhD8xhDQ39r3w=
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    repo: k0kubun/Nocturn
    tags: true
