matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: "9"
      env:
        - PACKAGE_PLATFORM=darwin

    - os: linux
      services: docker
      language: generic
      env:
        - PACKAGE_PLATFORM=win32

    - os: linux
      services: docker
      language: generic
      env:
        - PACKAGE_PLATFORM=darwin

cache:
  directories:
  - node_modules

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|YARN_|NPM_|CI|TRAVIS|BUILD_|PACKAGE_') \
        -v ${PWD}:/project k0kubun/node-wine:testing \
        /bin/bash -c "cd /project && yarn --link-duplicates --pure-lockfile && yarn build"
    else
      yarn build
    fi

  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|YARN_|NPM_|CI|TRAVIS|BUILD_|PACKAGE_') \
        -v ${PWD}:/project k0kubun/node-wine:testing \
        /bin/bash -c "cd /project && yarn package"
    else
      PACKAGE_PLATFORM=darwin yarn package
    fi
    find packages # testing, with k0kubun/node-wine:testing

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
