matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: '9'
      env:
        - PACKAGE_PLATFORM=darwin
    - os: linux
      services: docker
      language: generic
      env:
        - PACKAGE_PLATFORM=win32
    - os: linux
      services: docker
      language: generic
      env:
        - PACKAGE_PLATFORM=linux
cache:
  directories:
    - node_modules
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|YARN_|NPM_|CI|TRAVIS|BUILD_|PACKAGE_' | grep -v ' ') \
        -v ${PWD}:/project k0kubun/node-wine:latest \
        /bin/bash -c "cd /project && yarn --link-duplicates --pure-lockfile && yarn build"
    else
      yarn --link-duplicates --pure-lockfile
      yarn build
    fi

before_deploy:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|YARN_|NPM_|CI|TRAVIS|BUILD_|PACKAGE_' | grep -v ' ') \
        -v ${PWD}:/project k0kubun/node-wine:latest \
        /bin/bash -c "cd /project && yarn package"
    else
      yarn package
    fi
deploy:
  provider: releases
  api_key:
    # This is generated by `travis setup releases -r k0kubun/Nocturn`
    secure: DdNMIrWGNevS/LQZp9CIT8POq5ojLyyFthnq26atH12ac9VrvEi51I41FLz27xJ516cdyoYrdRXfId7/4nxuR/eLG8aaQoaztkrZ8rwSlnTUyakbTyyC9CYKCDMgwX9wSYzz6gK6USvl1M2/u7avwHdvNQUwsB9rAOVlS4dxqH/vT8LmzI5zjbQiCQ5jp1ICibkWAsx1I0cBHidBEQWZD2fhs1UhLKErH510fQghhK/q7PnSmgNg5jDVpMSFrsZPgid7dRqhOLBnrEbDDW4+DtHHHL3K2giy9ghJytjkPNC3MSg6zReYondDlJ69oDShHwzmW3AqoixhHPaLkG4mXN/f6RmrQ0tSGyQWdsOYh27sFGl136UBuwNUFLtyf/W4+LBCZQiedVcA6BcmIAADfI8u+ygm0WwE3OfWc7+XJeR43vz/kVAtPCHmKrqdkAkUqEy57Qcr4Y+0fv0VD3Kk+QOHcfH5TaTbZW2JpgzfOpQCUpWrl0xPa3OG8CrZ/MAIB4/+wOvAudapwu7eKMfenAZPMEbQ9X4Lio/KhzxcF3TDdBjcnshYS1Zu9mAnh63gylEc8slSt09QEBpDXsGYF5QUQWGXjfT6tsvpEKdPzZraViH/gtx6ogWfnUd24LRnXJPFaWjTl+T9PZVuVoi4cIpLsjSBUTCZSNHYRxKYHsM=
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    repo: k0kubun/Nocturn
    tags: true
