version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      #- run:
      #    name: yarn dist
      #    command: yarn dist --publish 'never'
      #- store_artifacts:
      #    path: dist
      #- persist_to_workspace:
      #    root: .
      #    paths:
      #      - dist

  release:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: echo hello
      #- attach_workspace:
      #    at: .
      #- run:
      #    name: Deploying to GitHub
      #    command: yarn dist


workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
